### ISSUE TITLE
What to change in packet in order to make compatible with 2.995

### ISSUE THREAD

**Issue by atomiclucky** [GrowtopiaNoobs/Growtopia-Bot#12]
Hello, after some time I found out that you need to change this packet in order to connect to the server:
```c++
SendPacket(2, "tankIDName|" + uname + "\ntankIDPass|" + upass + "\nrequestedName|SmileZero\nf|0\nprotocol|38\ngame_version|" + ver + "\nfz|13812200\nlmode|0\ncbits|0\nplayer_age|17\nGDPR|1\nhash2|"+hash2+"\nmeta|" + generateMeta() + "\nfhash|-716928004\nrid|" + generateRid() + "\nplatformID|0\ndeviceVersion|0\ncountry|us\nhash|" + hash + "\nmac|" + generateMac() + "\nwk|" + generateRid() + "\nzf|13837395" + token, peer);
```
here's some information i extracted by logging into my private server
tankIDName|username
tankIDPass|password
requestedName|BananaLaugh
f|1
protocol|71
game_version|2.995
fz|4396200
lmode|0
cbits|16
player_age|10
GDPR|2
hash2|1360193304
meta|localhost
fhash|-716928004
rid|01201DFC1FCA4FE7085FEEC520F23185
platformID|0
deviceVersion|0
country|lt
hash|-1664608105
mac|my mac address
reconnect|1
wk|022D7EF257F78C9F57A0EAD95401D922
zf|-1721288351
action|enter_game

**Comment by ardakurucim** [comment]
@atomiclucky i think hash is wrong

**Comment by InjectionZ** [comment]
i got this issue too

**Comment by atomiclucky** [comment]
@ardakurucim there's nothing wrong with it, i changed it a bit and now it shows that i'm online. 

But now the bot is getting a packet type of 7 when the size is only 5.

What should I do?

**Comment by atomiclucky** [comment]
Yes everything is working
