### ISSUE TITLE
I've change the gameVersion to 2.995 in source, but it shows up as outdated client for server.

### ISSUE THREAD

**Issue by Joiubaxas** [GrowtopiaNoobs/Growtopia-Bot#16]
I've change the gameVersion to 2.995 in source, but it shows up as outdated client for server when I add a bot. What else do I have to change to make growtopia server accept the bot as an up to date client?

**Comment by Joiubaxas** [comment]
Solved the problem

**Comment by RefetB** [comment]
@Joiubaxas Can you help me a bit?
