### ISSUE TITLE
How do i compile it?

### ISSUE THREAD

**Issue by JadlionHD** [GrowtopiaNoobs/Growtopia-Bot#19]
Okay so while i'm trying to build this is appear
![kjnsd](https://user-images.githubusercontent.com/48410066/65434091-6b41d980-de48-11e9-90d5-b7951d2f44ca.PNG)
how do i fix this issue?

**Comment by herothedev** [comment]
Un eed to download vs2013 and put compiler (c:/program files/visual studio 12.0/bin/link.exe is the compiler)

**Comment by JadlionHD** [comment]
Thanks for the info.

**Comment by Deveytv** [comment]
OwO

**Comment by JadlionHD** [comment]
> Un eed to download vs2013 and put compiler (c:/program files/visual studio 12.0/bin/link.exe is the compiler)

where should i put the link.exe?

**Comment by FliqXs** [comment]
> > Un eed to download vs2013 and put compiler (c:/program files/visual studio 12.0/bin/link.exe is the compiler)
> 
> where should i put the link.exe?

 Probably here (D:\Qt\5.3\Src\qtwebkit\Source\ThirdParty\ANGLE\src\compiler)
 and here but i don't know (D:\Qt\5.3\Src\qtdeclarative\src\qml\compiler)

**Comment by herothedev** [comment]
You need to go Projects->Manage Kits...->Compilers and add manually it there.

**Comment by JadlionHD** [comment]
Just found the problem. Alright thanks for commenting. -Closing issue-
