### ISSUE TITLE
[Q] Why i cant connect to real gt server?

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/Growtopia-Bot#20]
So why i cant connect to real gt server, i already updated my protocol to 72 so did rral gt port change or what?

**Comment by NotDark** [comment]
ip change

**Comment by herothedev** [comment]
what is the newest?

**Comment by aj22r** [comment]
The ip didn't change, it's still the same (209.59.190.105)

**Comment by moanhawks** [comment]
> what is the newest?

Pls check it out this link http://growtopia1.com/growtopia/server_data.php 
Make sure you don't connect any Private server

**Comment by ardakurucim** [comment]
209.59.190.105

**Comment by herothedev** [comment]
whats wrong then?

**Comment by herothedev** [comment]
#21 fix to problem ~~closing~~
