### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by JadlionHD** [GrowtopiaNoobs/Growtopia-Bot#22]
When im trying to connect the bot to the growtopia and send them to the world, the bot wont come, its because of game version or something?

**Comment by herothedev** [comment]
#21 -- fix

**Comment by ardakurucim** [comment]
@JadlionHD change protocol to 80

**Comment by JadlionHD** [comment]
@herothedev i been changed the ip and it goes nothing, the bot still cant connect to the gt. @ardakurucim is that will work?

**Comment by Valkr1e** [comment]
@JadlionHD No

**Comment by JadlionHD** [comment]
> @JadlionHD No

@Valkr1e how?
