### ISSUE TITLE
Adding Punch..

### ISSUE THREAD

**Issue by RefetB** [GrowtopiaNoobs/Growtopia-Bot#24]
There is a way to simulate punch to all bots?If the answer is yes,how can I  add it : D

**Comment by NotDark** [comment]
yes

**Comment by RefetB** [comment]
> 
> 
> yes

How can I?Can you explain it ?

**Comment by NotDark** [comment]
> How can I add it?Can you explain it ?@NotDark
> *I know I need send packets for punchs.(packet type 3,id 18 and x,y)
> But I facked about coding it.( : D).I'm looking for that code line to add...
> 
> **Edit = I can send punch visuals now but they r not breaking something :D...

just see in private server source
