### ISSUE TITLE
How can I fix this problem?

### ISSUE THREAD

**Issue by MainCmd** [GrowtopiaNoobs/Growtopia-Bot#25]
![how can i fix fking problem](https://user-images.githubusercontent.com/55925889/69340543-ce00f700-0c78-11ea-821c-67ca7748d2a2.PNG)

I changed ip and port but I still get this error and the bot doesn't come to world

**Comment by WoofHax** [comment]
Did you change Version 2.98 to 2.998?

**Comment by MainCmd** [comment]
I changed
