### ISSUE TITLE
[HELP NEEDED] Qt Problem

### ISSUE THREAD

**Issue by DrKfir** [GrowtopiaNoobs/Growtopia-Bot#26]
I'm kind of new in this stuff and I don't know how to even launch this so I need help can someone help me please, I'm new in this. There is a tutorial to this or someone can just explain to me how to build that without solution.
Do I need this .net framework to visual studio?

**Comment by ardakurucim** [comment]
@DrKfir download vs 2013 and click build project use release

**Comment by DrKfir** [comment]
@ardakurucim can you please send me a setup exe of vs2013 I don't find one

**Comment by ardakurucim** [comment]
https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by DrKfir** [comment]
> https://visualstudio.microsoft.com/vs/older-downloads/

@ardakurucim this URL doesn't work anymore

**Comment by JadlionHD** [comment]
you need to install visual studio 2013

**Comment by DrKfir** [comment]
> you need to install visual studio 2013

oh, now I understand I need to join to the "Dev Essentials program" now I'm downloading this after this I will check what @ardakurucim says

**Comment by DrKfir** [comment]
someone here knows what is this problem:


![Screenshot_9](https://user-images.githubusercontent.com/46719896/69898040-80f9e080-135c-11ea-890c-b85581c99e60.png)

**Comment by ardakurucim** [comment]
@DrKfir download vs2013 but dont open source with it open it with qt project

**Comment by DrKfir** [comment]
> @DrKfir download vs2013 but dont open source with it open it with qt project

I don't open-source with that it's the install problem and I have the same problem as #19 but I don't have the link.exe for this

**Comment by DrKfir** [comment]
do you have discord?

**Comment by ardakurucim** [comment]
nope

**Comment by DrKfir** [comment]
Now I have this problem:


![Screenshot_8](https://user-images.githubusercontent.com/46719896/69903713-e0301300-13a5-11ea-9fc8-88af28fdc090.png)

**Comment by DrKfir** [comment]
ok close issues
