### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ipadtopia** [GrowtopiaNoobs/Growtopia-Bot#29]
So when i try to debug, or ctrl + r, this error shows, but i alr install visual studio 2013, but still not working. Does anybody know how to fix it?
![image](https://user-images.githubusercontent.com/50906542/69921950-0c44b480-14ca-11ea-93e8-6dbc254066af.png)

**Comment by Ipadtopia** [comment]
Nvm fixed it closing..

**Comment by JadlionHD** [comment]
Alright then.
