### ISSUE TITLE
[Console Version] Growtopia Bot

### ISSUE THREAD

**Issue by DrOreo002** [GrowtopiaNoobs/Growtopia-Bot#32]
First of all, sorry for out of topic discussion. I know this isn't an issue but well I saw that many of users had a problem with building the project. So I decided to share my console version of the bot here. Thanks

```
Tired of compilling with qt?, hard to configure?
yall can try my console version of this repo https://github.com/DrOreo002/GrowtopiaBot
(Can be compiled directly after cloning using VsCode)
```
Full credit is given to @GrowtopiaNoobs cus I do not own the code

**Comment by WoofHax** [comment]
Good jobs 👌

**Comment by herothedev** [comment]
you should use cin for the owner setting and etc. instead of a file. or then cin + file combined

**Comment by MoanHawks** [comment]
config.json 😳

**Comment by DrOreo002** [comment]
> you should use cin for the owner setting and etc. instead of a file. or then cin + file combined

Typing every time when the bot started?, hell no

**Comment by herothedev** [comment]
i

> > you should use cin for the owner setting and etc. instead of a file. or then cin + file combined
> 
> Typing every time when the bot started?, hell no

i meant like cin for version and owner, but not bot accounts.

**Comment by impacts2** [comment]
> 
> 
> First of all, sorry for out of topic discussion. I know this isn't an issue but well I saw that many of users had a problem with building the project. So I decided to share my console version of the bot here. Thanks
> 
> ```
> Tired of compilling with qt?, hard to configure?
> yall can try my console version of this repo https://github.com/DrOreo002/GrowtopiaBot
> (Can be compiled directly after cloning using VsCode)
> ```
> 
> Full credit is given to @GrowtopiaNoobs cus I do not own the code
bro it keeps closing after i build it pls help

**Comment by DrOreo002** [comment]
> > First of all, sorry for out of topic discussion. I know this isn't an issue but well I saw that many of users had a problem with building the project. So I decided to share my console version of the bot here. Thanks
> > ```
> > Tired of compilling with qt?, hard to configure?
> > yall can try my console version of this repo https://github.com/DrOreo002/GrowtopiaBot
> > (Can be compiled directly after cloning using VsCode)
> > ```
> > 
> > 
> > Full credit is given to @GrowtopiaNoobs cus I do not own the code
> > bro it keeps closing after i build it pls help

The project is discontinued, I couldn't help you with that. Sorry
