### ISSUE TITLE
Can't download 5.3.2

### ISSUE THREAD

**Issue by herothedev** [GrowtopiaNoobs/Growtopia-Bot#36]
Hey, the link whats been provided on README.md doesn't have the 5.3.2 download anymore, neither google, i tried searching: "QT 5.3.2 download" etc. and i didn't find any. So please provide me a download link, or if this does work on newer version of QT msvc, then provide me a download link of it. 

Thanks,
Hero

**Comment by axnanyt** [comment]
http://ftp.fau.de/qtproject/archive/qt/5.14/5.14.1/ 
heres the link for latest

**Comment by GuckTubeYT** [comment]
> 
> 
> http://ftp.fau.de/qtproject/archive/qt/5.14/5.14.1/
> heres the link for latest

2.4 gb wtf
