### ISSUE TITLE
sfml-graphics-d.lib(sfml-graphics-d-2.dll):-1: error: LNK1112: module machine type 'X86' conflicts with target machine type 'x64'

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/Growtopia-Bot#37]
sfml-graphics-d.lib(sfml-graphics-d-2.dll): -1: error: LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
how to fix that

**Comment by herothedev** [comment]
use x32

**Comment by GuckTubeYT** [comment]
i do use x32 at visual studio, doesnt work

**Comment by herothedev** [comment]
this is qt project

**Comment by GuckTubeYT** [comment]
oh, thanks bro
