### ISSUE TITLE
How to fix disconnect problem?

### ISSUE THREAD

**Issue by RefetB** [GrowtopiaNoobs/Growtopia-Bot#39]
My bots getting dc per 5 min.There is a fix?

**Comment by RefetB** [comment]
@DrOreo002 Maybe you know the solution?I think there is sending ping is missing.If you know what to do can answer me?

**Comment by DrOreo002** [comment]
Yes you have to answer ping by server

**Comment by RefetB** [comment]
@DrOreo002 Can you help a bit about it?

**Comment by DrOreo002** [comment]
I'm no longer developing bot, sorry

**Comment by RefetB** [comment]
@DrOreo002 Atleast can you explain how to do that?It will be great to hear...

**Comment by DrOreo002** [comment]
Already told you how, answer ping packet by the server

this should help ya https://github.com/GrowtopiaNoobs/GrowtopiaServer/issues/1103

**Comment by RefetB** [comment]
@DrOreo002 Thanks alot.I will try to fix it.
