### ISSUE TITLE
Needed package list

### ISSUE THREAD

**Issue by vonsogt** [GrowtopiaNoobs/Growtopia-Bot#4]
I've been trying so many version of Visual Studio 2010,2013 & 2017 and using QT you recommended but still error

**Comment by ritzysw** [comment]
your problem, and its pointless making issues, anybody quitted project long time ago

**Comment by SecretHax** [comment]
>your problem, and its pointless making issues, anybody quitted project long time ago

@ritzysw Wow, responding „ur problem” to an issue... genius

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ritzysw** [comment]
Did you come back for another dose of bullying or what

**Comment by GrowtopiaNoobs** [comment]
What errors do you get?

**Comment by vonsogt** [comment]
> What errors do you get?

Cannot compile not compatible with the version of VS
