### ISSUE TITLE
How to take dropped items?

### ISSUE THREAD

**Issue by RefetB** [GrowtopiaNoobs/Growtopia-Bot#41]
How bots can take dropped items?I know I need to send a packet to request collecting.But I dont know how to do..

**Comment by SpaceR3** [comment]
Use a Proxy to see what packet it sends when you collect something

**Comment by RefetB** [comment]
@SpaceR3 I know what is going on when you drop/take something at game...But there is something called itemNetid to collect items.I dont know how to learn it ..
