### ISSUE TITLE
How do I add something to the bot?

### ISSUE THREAD

**Issue by Mr4sR** [GrowtopiaNoobs/Growtopia-Bot#48]
How do I add commands?
like being able to check gems on bots, buy something in the store with gems, and so on?
Is there a tool to record what system I just did growtopia?

**Comment by DrOreo002** [comment]
Understand growtopia's packet first. There's no easy way of doing it, you gotta find it manually by using proxy (Check out GrowbrewProxy). There's no magic tools, at least a good knowledge of programming, networking (working with packets), and brain is needed
