### ISSUE TITLE
How I merge all files to a simple exe file?

### ISSUE THREAD

**Issue by Greanex** [GrowtopiaNoobs/Growtopia-Bot#8]
I have so much questions. This is only one of my all questions. I'm beginner in this and I don't know yet how I can make a exe file with these files. Can someone help me, please?

**Comment by atomiclucky** [comment]
bruh

**Comment by Greanex** [comment]
What? I already said I'm beginner and I need some help, please..

**Comment by atomiclucky** [comment]
do you now know how to merge???

**Comment by Greanex** [comment]
No bro. Can help?

**Comment by Greanex** [comment]
I don't know how to merge exactly but there's an option called "Build Growtopia_Bot" and "Build". Can I merge with this options?
